version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - zk_network

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - zk_network

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - zk_network

  scout1:
    build: .
    hostname: scout1
    environment:
      ZK_SERVER: zoo1,zoo2,zoo3
      ZK_TIMEOUT: 20
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    networks:
      - zk_network

  scout2:
    build: .
    hostname: scout2
    environment:
      ZK_SERVER: zoo1,zoo2,zoo3
      ZK_TIMEOUT: 20
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    networks:
      - zk_network

  scout3:
    build: .
    hostname: scout3
    environment:
      ZK_SERVER: zoo1,zoo2,zoo3
      ZK_TIMEOUT: 20
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    networks:
      - zk_network

  scout4:
    build: .
    hostname: scout4
    environment:
      ZK_SERVER: zoo1,zoo2,zoo3
      ZK_TIMEOUT: 20
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    networks:
      - zk_network

  scout5:
    build: .
    hostname: scout5
    environment:
      ZK_SERVER: zoo1,zoo2,zoo3
      ZK_TIMEOUT: 20
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    networks:
      - zk_network
networks:
  zk_network:
    external: true